version: '3.8'

services:
  minecraft:
    build: .
    container_name: minecraft-server-vanilla
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${SERVER_PORT:-25565}:25565"
      - "${RCON_PORT:-25575}:25575"
    volumes:
      - minecraft_data-vanilla:/data
    environment:
      # Override any environment variables here if needed
      # or use the .env file for customization
      TZ: "America/New_York"  # Set your timezone
    stdin_open: true
    tty: true
    # Resource limits based on environment variables
    deploy:
      resources:
        limits:
          memory: ${MEMORY:-2G}
          cpus: '${CPU_LIMIT:-2.0}'

volumes:
  minecraft_data-vanilla:
    driver: local